/*
 * p43_scenes.h — P4.3 固件内嵌场景 AppState（由 firmware/tools/gen_p43_scenes.py
 * 生成，勿手改）。来源（只读真源）：
 *   S01_idle/S03_working/S05_needs_you/S19_usage_0/S20_usage_100 的 app_state
 *   payload（tests/fixtures/scenarios，与 golden 同源）+
 *   tests/fixtures/protocol/valid_full.json（协议 fixture，覆盖 CJK 与
 *   needs_you+plan 混合形态）。
 * 重序列化仅做紧凑化（语义等价）；两端（固件/模拟器对齐脚本）解析同一文本。
 */
#ifndef P43_SCENES_H
#define P43_SCENES_H

/* 507 bytes UTF-8 */
static const char P43_SCENE_IDLE_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"scenario-001\",\"seq\":1,\"generated_at_ms\":1789000000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789000000000},\"selected_thread_id\":null,\"threads_total\":0,\"threads_truncated\":false,\"threads\":[],\"usage\":{\"available\":true,\"updated_at_ms\":1789000000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"codex-primary\",\"label\":\"300 MIN WINDOW\",\"used_percent\":42.0,\"duration_mins\":300,\"resets_at_ms\":1789003600000}]}}";

/* 999 bytes UTF-8 */
static const char P43_SCENE_WORKING_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"scenario-001\",\"seq\":1,\"generated_at_ms\":1789000000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789000000000},\"selected_thread_id\":\"thread-demo\",\"threads_total\":1,\"threads_truncated\":false,\"threads\":[{\"id\":\"thread-demo\",\"turn_id\":\"turn-001\",\"project\":\"codex-desk-terminal\",\"state\":\"working\",\"activity\":\"正在运行构建与测试\",\"updated_at_ms\":1789000000000,\"elapsed_ms\":0,\"waiting_ms\":0,\"end_reason\":null,\"attention\":null,\"plan\":{\"total\":3,\"truncated\":false,\"steps\":[{\"text\":\"检查需求\",\"status\":\"completed\"},{\"text\":\"实现界面\",\"status\":\"in_progress\"},{\"text\":\"运行测试\",\"status\":\"pending\"}]},\"context\":{\"used_tokens\":null,\"capacity_tokens\":null,\"used_percent\":null}}],\"usage\":{\"available\":true,\"updated_at_ms\":1789000000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"codex-primary\",\"label\":\"300 MIN WINDOW\",\"used_percent\":42.0,\"duration_mins\":300,\"resets_at_ms\":1789003600000}]}}";

/* 916 bytes UTF-8 */
static const char P43_SCENE_NEEDS_YOU_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"scenario-001\",\"seq\":1,\"generated_at_ms\":1789000000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789000000000},\"selected_thread_id\":\"thread-demo\",\"threads_total\":1,\"threads_truncated\":false,\"threads\":[{\"id\":\"thread-demo\",\"turn_id\":\"turn-001\",\"project\":\"codex-desk-terminal\",\"state\":\"needs_you\",\"activity\":\"等待批准运行命令\",\"updated_at_ms\":1789000000000,\"elapsed_ms\":0,\"waiting_ms\":0,\"end_reason\":null,\"attention\":{\"pending_count\":1,\"summary\":\"运行命令需要批准\"},\"plan\":{\"total\":0,\"truncated\":false,\"steps\":[]},\"context\":{\"used_tokens\":null,\"capacity_tokens\":null,\"used_percent\":null}}],\"usage\":{\"available\":true,\"updated_at_ms\":1789000000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"codex-primary\",\"label\":\"300 MIN WINDOW\",\"used_percent\":42.0,\"duration_mins\":300,\"resets_at_ms\":1789003600000}]}}";

/* 998 bytes UTF-8 */
static const char P43_SCENE_USAGE0_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"scenario-001\",\"seq\":1,\"generated_at_ms\":1789000000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789000000000},\"selected_thread_id\":\"thread-demo\",\"threads_total\":1,\"threads_truncated\":false,\"threads\":[{\"id\":\"thread-demo\",\"turn_id\":\"turn-001\",\"project\":\"codex-desk-terminal\",\"state\":\"working\",\"activity\":\"正在运行构建与测试\",\"updated_at_ms\":1789000000000,\"elapsed_ms\":0,\"waiting_ms\":0,\"end_reason\":null,\"attention\":null,\"plan\":{\"total\":3,\"truncated\":false,\"steps\":[{\"text\":\"检查需求\",\"status\":\"completed\"},{\"text\":\"实现界面\",\"status\":\"in_progress\"},{\"text\":\"运行测试\",\"status\":\"pending\"}]},\"context\":{\"used_tokens\":null,\"capacity_tokens\":null,\"used_percent\":null}}],\"usage\":{\"available\":true,\"updated_at_ms\":1789000000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"codex-primary\",\"label\":\"300 MIN WINDOW\",\"used_percent\":0.0,\"duration_mins\":300,\"resets_at_ms\":1789014400000}]}}";

/* 1000 bytes UTF-8 */
static const char P43_SCENE_USAGE100_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"scenario-001\",\"seq\":1,\"generated_at_ms\":1789000000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789000000000},\"selected_thread_id\":\"thread-demo\",\"threads_total\":1,\"threads_truncated\":false,\"threads\":[{\"id\":\"thread-demo\",\"turn_id\":\"turn-001\",\"project\":\"codex-desk-terminal\",\"state\":\"working\",\"activity\":\"正在运行构建与测试\",\"updated_at_ms\":1789000000000,\"elapsed_ms\":0,\"waiting_ms\":0,\"end_reason\":null,\"attention\":null,\"plan\":{\"total\":3,\"truncated\":false,\"steps\":[{\"text\":\"检查需求\",\"status\":\"completed\"},{\"text\":\"实现界面\",\"status\":\"in_progress\"},{\"text\":\"运行测试\",\"status\":\"pending\"}]},\"context\":{\"used_tokens\":null,\"capacity_tokens\":null,\"used_percent\":null}}],\"usage\":{\"available\":true,\"updated_at_ms\":1789000000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"codex-primary\",\"label\":\"300 MIN WINDOW\",\"used_percent\":100.0,\"duration_mins\":300,\"resets_at_ms\":1789003600000}]}}";

/* 1065 bytes UTF-8 */
static const char P43_SCENE_VALID_FULL_JSON[] = "{\"schema_version\":1,\"kind\":\"state\",\"bridge_epoch\":\"mock-run-001\",\"seq\":7,\"generated_at_ms\":1789002000000,\"source\":{\"kind\":\"mock\",\"connected\":true,\"stale\":false,\"last_event_at_ms\":1789002000000},\"selected_thread_id\":\"thread-demo\",\"threads_total\":1,\"threads_truncated\":false,\"threads\":[{\"id\":\"thread-demo\",\"turn_id\":\"turn-001\",\"project\":\"codex-desk-terminal\",\"state\":\"needs_you\",\"activity\":\"请在电脑上处理权限请求\",\"updated_at_ms\":1789002000000,\"elapsed_ms\":120000,\"waiting_ms\":5000,\"end_reason\":null,\"attention\":{\"pending_count\":1,\"summary\":\"运行命令需要批准\"},\"plan\":{\"total\":3,\"truncated\":false,\"steps\":[{\"text\":\"检查需求\",\"status\":\"completed\"},{\"text\":\"实现界面\",\"status\":\"in_progress\"},{\"text\":\"运行测试\",\"status\":\"pending\"}]},\"context\":{\"used_tokens\":null,\"capacity_tokens\":null,\"used_percent\":null}}],\"usage\":{\"available\":true,\"updated_at_ms\":1789002000000,\"windows_total\":1,\"windows_truncated\":false,\"windows\":[{\"id\":\"quota-example\",\"label\":\"SHORT WINDOW\",\"used_percent\":42.0,\"duration_mins\":300,\"resets_at_ms\":1789012800000}]}}";

#endif /* P43_SCENES_H */
